{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeassume.fullname" . }}
  labels:
    {{- include "kubeassume.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
